#!/usr/bin/env bash

# ANSI colors
cnone="$(echo -ne '\033[0m')"
cwhiteb="$(echo -ne '\033[1;37m')"
cwhite="$(echo -ne '\033[0;37m')"
cgray="$(echo -ne '\033[1;30m')"
cblack="$(echo -ne '\033[0;30m')"

cred="$(echo -ne '\033[0;31m')"
credb="$(echo -ne '\033[1;31m')"
cgreen="$(echo -ne '\033[0;32m')"
cgreenb="$(echo -ne '\033[1;32m')"
cyellow="$(echo -ne '\033[0;33m')"
cyellowb="$(echo -ne '\033[1;33m')"
cblue="$(echo -ne '\033[0;34m')"
cblueb="$(echo -ne '\033[1;34m')"
cmagenta="$(echo -ne '\033[0;35m')"
cmagentab="$(echo -ne '\033[1;35m')"
ccyan="$(echo -ne '\033[0;36m')"
ccyanb="$(echo -ne '\033[1;36m')"


echo
echo "${cblue}***** New Lesson *****${cnone}"
echo "Please read the ${cred}README (Creating New Content)${cnone} for guidelines!"
echo
echo "Enter the ${cgreen}number${cnone} of the lesson's topic:"
#read -e -p "${cwhiteb}>${cnone} " topic
topics=$(for folder in topics/*/; do basename $folder; done)
# Change their PS3
OLD_PS3="$PS3"
export PS3="Choice number ${cwhiteb}>${cnone} "
topic=""
until [ -n "$topic" ]; do
  select topic in $topics; do break; done
done
export PS3="$OLD_PS3"

echo "Enter the lesson's title (${cgreen}ex: \"Using Files & Commands\"${cnone}):"
read -e -p "${cwhiteb}>${cnone} " title

echo "Enter the title's slug (${cgreen}ex: files-commands${cnone}):"
read -e -p "${cwhiteb}>${cnone} " slug

order=$(find topics/$topic/*/ -type f 2> /dev/null | xargs cat | grep -I 'order:' | sort -r | head -n 1 | cut -c 8-)
if [ -z "$order" ]; then
  order="0"
fi
let "next = $order + 1"

echo
echo "Creating new lesson..."
octopress new page topics/$topic/$slug/ \
  --title "$title" \
  --template lesson \
  --config _octopress.yml

if [ "$?" != 0 ]; then
  echo "${cred}Error creating lesson page.${cnone}"
  exit 1
fi

cp topics/$topic/$slug/index.md topics/$topic/$slug/index.md.tmp

cat topics/$topic/$slug/index.md.tmp |\
  sed -e "s/group:/group: $topic/" |\
  sed -e "s/order:/order: $next/" |\
  sed -e "s/Title/$title/" > topics/$topic/$slug/index.md

rm topics/$topic/$slug/index.md.tmp
echo "${cgreen}Lesson page created.${cnone}"

