#!/usr/bin/env bash

# ANSI colors
cnone="$(echo -ne '\033[0m')"
cwhiteb="$(echo -ne '\033[1;37m')"
cwhite="$(echo -ne '\033[0;37m')"
cgray="$(echo -ne '\033[1;30m')"
cblack="$(echo -ne '\033[0;30m')"

cred="$(echo -ne '\033[0;31m')"
credb="$(echo -ne '\033[1;31m')"
cgreen="$(echo -ne '\033[0;32m')"
cgreenb="$(echo -ne '\033[1;32m')"
cyellow="$(echo -ne '\033[0;33m')"
cyellowb="$(echo -ne '\033[1;33m')"
cblue="$(echo -ne '\033[0;34m')"
cblueb="$(echo -ne '\033[1;34m')"
cmagenta="$(echo -ne '\033[0;35m')"
cmagentab="$(echo -ne '\033[1;35m')"
ccyan="$(echo -ne '\033[0;36m')"
ccyanb="$(echo -ne '\033[1;36m')"


echo
echo "${cblue}***** New Lesson *****${cnone}"
echo "Please read the ${cred}README${cnone} for guidelines!"
echo
echo "Enter the lesson's topic (${cgreen}ex: terminal-usage${cnone}):"
echo -n "${cwhiteb}>${cnone} "
read -e topic

echo "Enter the lesson's title (${cgreen}ex: \"Using Files & Commands\"${cnone}):"
echo -n "${cwhiteb}>${cnone} "
read -e title

echo "Enter the title's slug (${cgreen}ex: files-commands${cnone}):"
echo -n "${cwhiteb}>${cnone} "
read -e slug

order=$(find topics/$topic/*/ -type f 2> /dev/null | xargs cat | grep 'order:' | sort -r | head -n 1 | cut -c 8-)
if [ -z "$order" ]; then
  order="0"
fi
let "next = $order + 1"

echo
echo "Creating new lesson..."
octopress new page topics/$topic/$slug/ --title "$title" --template lesson

cp topics/$topic/$slug/index.md topics/$topic/$slug/index.md.tmp

cat topics/$topic/$slug/index.md.tmp |\
  sed -e "s/group:/group: $topic/" |\
  sed -e "s/order:/order: $next/" |\
  sed -e "s/Title/$title/" > topics/$topic/$slug/index.md

rm topics/$topic/$slug/index.md.tmp
echo "${cgreen}Lesson page created.${cnone}"

