#!/usr/bin/env bash

# ANSI colors
cnone="$(echo -ne '\033[0m')"
cwhiteb="$(echo -ne '\033[1;37m')"
cwhite="$(echo -ne '\033[0;37m')"
cgray="$(echo -ne '\033[1;30m')"
cblack="$(echo -ne '\033[0;30m')"

cred="$(echo -ne '\033[0;31m')"
credb="$(echo -ne '\033[1;31m')"
cgreen="$(echo -ne '\033[0;32m')"
cgreenb="$(echo -ne '\033[1;32m')"
cyellow="$(echo -ne '\033[0;33m')"
cyellowb="$(echo -ne '\033[1;33m')"
cblue="$(echo -ne '\033[0;34m')"
cblueb="$(echo -ne '\033[1;34m')"
cmagenta="$(echo -ne '\033[0;35m')"
cmagentab="$(echo -ne '\033[1;35m')"
ccyan="$(echo -ne '\033[0;36m')"
ccyanb="$(echo -ne '\033[1;36m')"


echo
echo "${cblue}***** New Topic *****${cnone}"
echo "Please read the ${cred}README (Creating New Content)${cnone} for guidelines!"
echo
echo "Enter the topic's title (${cgreen}ex: \"Terminal Usage\"${cnone}):"
read -e -p "${cwhiteb}>${cnone} " title

echo "Enter the topic's slug (${cgreen}ex: terminal-usage${cnone}):"
read -e -p "${cwhiteb}>${cnone} " topic

order=$(cat topics/*/index.md | grep 'order:' | sort -r | head -n 1 | cut -c 8-)
if [ -z "$order" ]; then
  order="0"
fi
let "next = $order + 1"

echo
echo "Creating new topic..."
octopress new page topics/$topic/ \
  --title "$title" \
  --template topic \
  --config _octopress.yml

if [ "$?" != 0 ]; then
  echo "${cred}Error creating lesson page.${cnone}"
  exit 1
fi

cp topics/$topic/index.md topics/$topic/index.md.tmp

cat topics/$topic/index.md.tmp |\
  sed -e "s/topic:/topic: $topic/" |\
  sed -e "s/order:/order: $next/" |\
  sed -e "s/Title/$title/" > topics/$topic/index.md

rm topics/$topic/index.md.tmp
echo "${cgreen}Lesson page created.${cnone}"
